### ISSUE TITLE
v0.0.16 Controller fails to create/update a Lattice Service when no endpoints in any of the corresponding K8S Services

### ISSUE THREAD

**Issue by klyubin** [aws/aws-application-networking-k8s#386]
Steps to reproduce:
1. Create a K8S HTTPRoute pointed at a Lattice Gateway as the parent and, as the backend, a K8S Service whose selectors don't match any endpoints.
2. Observe that the Controller is unable to create (or update) the Lattice Service, and keeps spewing the following:
```json
{"level":"info","ts":1693939293.0518966,"logger":"controller.route","caller":"controllers/route_controller.go:312","msg":"RouteReconciler: Failed deploy traffic-exemplar due to err TargetSynthesize: Failed to create targets :&{{0xc012a2d000 AWS:VPCServiceNetwork::Targets k8s-traffic-exemplar-traffic-exemplar} {traffic-exemplar traffic-exemplar traffic-exemplar  []}} , err:InvalidParameter: 1 validation error(s) found.\n- missing required field, RegisterTargetsInput.Targets.\n\n"}
```

It appears that the Controller is calling some API which does not let it provide an empty list of Targets for a Target Group. Strangely, the AWS Console does let me create/update Target Groups without any targets. So, it seems the Controller has a bug.

**Comment by solmonk** [comment]
Thanks for reporting this issue.

Relevant: https://github.com/aws/aws-application-networking-k8s/blob/main/pkg/deploy/stack_deployer.go#L120-L133

I had a quick look, I feel like this is not a v0.0.16 regression and the controller has been working like this since the beginning. The controller cannot proceed to service reconciliation if it cannot finish target registration, and I don't recall any validation logic that prevents empty RegisterTargets request.

**Comment by mikhail-aws** [comment]
Hints for fix:
- https://github.com/aws/aws-application-networking-k8s/blob/main/pkg/deploy/lattice/targets_synthesizer.go#L43-L44
- check if list is empty

**Comment by klyubin** [comment]
Thank you very much!
